sudo: required

services:
  - docker

before_install:
  - docker build -t peinutz/multicontainer-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true peinutz/multicontainer-client npm test

after_success:
  - docker build -t  peinutz/multicontainer-client ./client
  - docker build -t peinutz/multicontainer-server ./server
  - docker build -t peinutz/multicontainer-worker ./worker
  - docker build -t peinutz/multicontainer-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push peinutz/multicontainer-client
  - docker push peinutz/multicontainer-nginx
  - docker push peinutz/multicontainer-server
  - docker push peinutz/multicontainer-worker
