sudo: required

services:
  - docker

before_install:
  - docker build -t peinutz/multicontainer-client -f ./client/Dockerfile.dev ./

script:
  - docker run -e CI=true peinutz/multicontainer-client npm test

after_success:
  - docker build -t  peinutz/multicontainer-client ./client
  - docker build -t peinutz/multicontainer-server ./server
  - docker build -t peinutz/multicontainer-worker ./worker
  - docker build -t peinutz/multicontainer-nginx ./nginx
